# Generated by Django 4.2.3 on 2024-04-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_qna',
            old_name='index',
            new_name='idx',
        ),
    ]
